name: PirateRadio
options:
  bundleIdPrefix: com.pirateradio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "A9738D53DZ"
    MARKETING_VERSION: "0.1.1"
    CURRENT_PROJECT_VERSION: "1"

targets:
  PirateRadio:
    type: application
    platform: iOS
    sources:
      - PirateRadio
    resources:
      - path: PirateRadio/Resources
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        INFOPLIST_FILE: PirateRadio/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pirateradio.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    entitlements:
      path: PirateRadio/Resources/PirateRadio.entitlements
    dependencies:
      - package: SpotifyiOS
      - package: Kronos
    scheme:
      testTargets:
        - PirateRadioTests

  PirateRadioTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PirateRadioTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: PirateRadio

packages:
  SpotifyiOS:
    url: https://github.com/spotify/ios-sdk
    from: "5.0.1"
  Kronos:
    url: https://github.com/MobileNativeFoundation/Kronos
    from: "4.2.2"
